In [1]:
import pandas as pd

FILE = r'C:\Users\seo\Downloads\sample_data.csv'
df = pd.read_csv(FILE)

In [14]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt



---
1. 분류 -> 품종 분류

In [3]:
df.head()

Length  Weight Species
0    25.4   242.0  B-Type
1    26.3   290.0  B-Type
2    26.5   340.0  B-Type
3    29.0   363.0  B-Type
4    29.0   430.0  B-Type

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Length   49 non-null     float64
 1   Weight   49 non-null     float64
 2   Species  49 non-null     object 
dtypes: float64(2), object(1)
memory usage: 1.3+ KB


In [5]:
df.isnull().sum()

Length     0
Weight     0
Species    0
dtype: int64

In [6]:
df.columns

Index(['Length', 'Weight', 'Species'], dtype='object')

In [9]:
df.Species.value_counts()

B-Type    35
S-Type    14
Name: Species, dtype: int64

In [13]:
data = df[df.columns[:-1]]
target = df[df.columns[-1]]

x_train, x_test, y_train, y_test = train_test_split(data, target, stratify=target, test_size=0.2)
len(x_train),len(y_train),len(x_test),len(y_test)


(39, 39, 10, 10)

In [15]:
model = KNeighborsClassifier()
params = {'n_neighbors':[2,3,4,5],'p':[1,2]}
grid = GridSearchCV(model,param_grid=params,cv=3,scoring='accuracy')
grid.fit(x_train,y_train)

c:\Users\seo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
c:\Users\seo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` t

GridSearchCV(cv=3, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [2, 3, 4, 5], 'p': [1, 2]},
             scoring='accuracy')

In [16]:
best_model = grid.best_estimator_

In [54]:
best_model.kneighbors()
#길이와 무게값을 알 수 있다.

(array([[ 5. ,  7. ],
        [ 9.1,  9.7],
        [21. , 41. ],
        [50.2, 53.5],
        [11. , 22.5],
        [ 0.6,  1.1],
        [ 1. ,  1.1],
        [ 1.1,  1.5],
        [ 1.4,  1.8],
        [29. , 46.5],
        [ 0.5,  0.8],
        [ 0.3,  1. ],
        [26.5, 31. ],
        [ 0.3,  1.1],
        [21. , 26. ],
        [11. , 11.5],
        [ 7.5, 25. ],
        [ 0. , 16. ],
        [ 0.3,  0.8],
        [ 0.8,  1.4],
        [48.9, 99.1],
        [11.5, 22.5],
        [ 5. , 12. ],
        [41. , 53.5],
        [25. , 25.3],
        [ 0.8,  1.8],
        [22.5, 25. ],
        [ 1.3,  1.7],
        [ 7. , 12. ],
        [ 0.6,  1.5],
        [27. , 35.5],
        [ 6. , 22. ],
        [48.9, 50.2],
        [31. , 31.5],
        [ 1. ,  1.3],
        [ 0.3,  0.5],
        [ 7.5, 22.5],
        [ 6. , 16. ],
        [ 0. , 16. ]]),
 array([[22, 28],
        [ 8, 25],
        [14, 23],
        [32, 23],
        [15, 21],
        [29,  7],
        [11, 13],
        [ 5, 2

In [17]:
y_pre = best_model.predict(x_test)

c:\Users\seo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [18]:
accuracy_score(y_pre,y_test)

1.0

In [19]:
y_pre

array(['B-Type', 'B-Type', 'S-Type', 'B-Type', 'B-Type', 'B-Type',
       'S-Type', 'B-Type', 'B-Type', 'S-Type'], dtype=object)

In [20]:
y_test

28    B-Type
3     B-Type
47    S-Type
24    B-Type
30    B-Type
14    B-Type
39    S-Type
13    B-Type
5     B-Type
41    S-Type
Name: Species, dtype: object

 ---
 2.회귀 -> 길이로 무게 예측
 

In [21]:
df.columns

Index(['Length', 'Weight', 'Species'], dtype='object')

In [34]:
data2 = df['Length'] #길이
target2 = df['Weight'] #무게
type(data2)


pandas.core.series.Series

In [41]:
data2

0     25.4
1     26.3
2     26.5
3     29.0
4     29.0
5     29.7
6     29.7
7     30.0
8     30.0
9     30.7
10    31.0
11    31.0
12    31.5
13    32.0
14    32.0
15    32.0
16    33.0
17    33.0
18    33.5
19    33.5
20    34.0
21    34.0
22    34.5
23    35.0
24    35.0
25    35.0
26    35.0
27    36.0
28    36.0
29    37.0
30    38.5
31    38.5
32    39.5
33    41.0
34    41.0
35     9.8
36    10.5
37    10.6
38    11.0
39    11.2
40    11.3
41    11.8
42    11.8
43    12.0
44    12.2
45    12.4
46    13.0
47    14.3
48    15.0
Name: Length, dtype: float64

In [38]:
import numpy as np

data3 = np.array(data2).reshape(-1,1)

In [52]:

x_train, x_test, y_train, y_test = train_test_split(data3, target2, stratify=target2, test_size=0.2)

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

In [48]:
model = KNeighborsRegressor()
params = {'n_neighbors':[2,3,4,5],'p':[1,2]}
grid = GridSearchCV(model,param_grid=params,cv=3,scoring='accuracy')
grid.fit(x_train,y_train)

c:\Users\seo\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\seo\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "c:\Users\seo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 216, in __call__
    return self._score(
  File "c:\Users\seo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "c:\Users\seo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\seo\anaconda3\lib\site-packages\sklearn\neighbors\_regression.py", line 238, in predict
    y_pred = np.mean(_y[neigh_ind], axis=1)
  File "<__array_functi

GridSearchCV(cv=3, estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': [2, 3, 4, 5], 'p': [1, 2]},
             scoring='accuracy')

In [50]:
best_regressor = grid.best_estimator_

In [51]:
y_pre = best_regressor.predict(x_test)

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [45]:
grid.predict([[35]])

array([690.])

In [82]:
data = df[['Length']]
#시리즈 형태로 들어오기 때문에, 2차원으로 바꾸어주어야한다.

target = df['Weight'] #무게
# target

In [83]:
x_train, x_test, y_train, y_test = train_test_split(data, target, random_state=1)

In [84]:
# 회귀모델객체생성
kegModel = KNeighborsRegressor()

In [72]:
len(x_train),len(y_train),len(x_test),len(y_test)
x_train.reshape(-1,1)

(36,)

In [ ]:
#5개의 평균값과 다른 이유는 가까이에 있는 애들이랑의 평균과 + 가중치가 각각 있기 때문에 다르다. 

In [77]:
x_train.reshape(-1,1)

AttributeError: 'Series' object has no attribute 'reshape'

In [85]:

# kegModel.fit(x_train.reshape(-1,1),y_train)
kegModel.fit(x_train,y_train)

KNeighborsRegressor()

In [86]:
kegModel.score(x_test,y_test)

0.9449929957289194

In [61]:
kegModel.predict([[32.7]])

c:\Users\seo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


ValueError: X has 1 features, but KNeighborsRegressor is expecting 2 features as input.