In [ ]:
# duplicate 중복제거
# 단위 환산
# 자료형 변환


<span style=color:red>
    <h2>데이터 표준화</h2>
    </span>

In [ ]:
# 결측치 체크 및 처리
# 중복 체크 및 처리
# 이상치 체크 및 처리
# 데이터 타입 정리 (실제 2.30 string => float 맞춰주기)
# 데이터 타입 변환 => 실제로 들어있는 값은 나이  32, => 범주형으로 바꾸고 싶다. 유아, 아동, 청소년으로 바꾸고 싶다. 
# 데이터 인코딩 처리 => (문자형 데이터 -> 숫자형
# 데이터 스케일링(수치 데이터 -> ) 어떤 모델들은 스케일링을 하지 않더라도 상관없다. ex) 이진트리 키가 180보다 큽니까? 

In [8]:
import pandas as pd
from numpy import nan

name = ["홍길동","이나영","마징가","변사또","원더우먼","현빈","원빈","박보검","김상민","김한림"]
age = [0,4,21,20,38,100,40,61,11,23]
gender = ["M","F","M","M","F","M","M","M","M","F"]

In [9]:
personDF = pd.DataFrame({'name':name,"age":age,"gender":gender})
personDF.head(5)

name  age gender
0   홍길동    0      M
1   이나영    4      F
2   마징가   21      M
3   변사또   20      M
4  원더우먼   38      F

In [10]:
personDF.dtypes

name      object
age        int64
gender    object
dtype: object

In [11]:
personDF["gender"].astype('category') #inplace가 없음
# personDF.gender.astype('category') #inplace가 없음 기본 object 타입을 => 카테고리타입으로 변경


0    M
1    F
2    M
3    M
4    F
5    M
6    M
7    M
8    M
9    F
Name: gender, dtype: category
Categories (2, object): ['F', 'M']

In [25]:
# 연속형 데이터 -> 범주형 데이터로 변환
# 나이를 범주형으로 바꾸면 대량의 범주가 생김 종류가 너무 많으니까 한 그룹으로 쓰려고 하는 것이니까.
# 범위 : 구간 
# cut(데이터, 구간정보, 구간라벨) => 범위 즉 구간 설정 => 범주로 변경
bins = [0,20,40,60,80,100]

# ret1,bins = pd.cut(personDF.age, bins=5,labels=['아동기',"청년","중년","장년","노년"],right=False, retbins=True) #retbins 구간 

ret1,bins = pd.cut(personDF.age, bins=bins,labels=['아동기',"청년","중년","장년","노년"],right=False, retbins=True) #retbins 구간 


In [16]:
ret1

0    아동기
1    아동기
2     청년
3    아동기
4     청년
5     노년
6     청년
7     장년
8    아동기
9     청년
Name: age, dtype: category
Categories (5, object): ['아동기' < '청년' < '중년' < '장년' < '노년']

In [20]:
ret1

(0    아동기
 1    아동기
 2     청년
 3     청년
 4     청년
 5     노년
 6     중년
 7     장년
 8    아동기
 9     청년
 Name: age, dtype: category
 Categories (5, object): ['아동기' < '청년' < '중년' < '장년' < '노년'],
 array([  0. ,  20. ,  40. ,  60. ,  80. , 100.1]))

In [24]:
bins #, 100.1 right=False 포함안시켜야한다. 그래야 101이 안들어간다.

array([  0. ,  20. ,  40. ,  60. ,  80. , 100.1])

In [26]:
ret1

# ret1,bins = pd.cut(personDF.age, bins=bins,labels=['아동기',"청년","중년","장년","노년"],right=False, retbins=True) #retbins 구간 
# NaN

0    아동기
1    아동기
2     청년
3     청년
4     청년
5    NaN
6     중년
7     장년
8    아동기
9     청년
Name: age, dtype: category
Categories (5, object): ['아동기' < '청년' < '중년' < '장년' < '노년']

In [27]:
ret1,bins = pd.cut(personDF.age, bins=bins,labels=['아동기',"청년","중년","장년","노년"],right=True, retbins=True) #retbins 구간 
ret1

#right=True 이면 왼쪽을 포함안시킴 그렇게 하니까 0은 사라짐

0    NaN
1    아동기
2     청년
3    아동기
4     청년
5     노년
6     청년
7     장년
8    아동기
9     청년
Name: age, dtype: category
Categories (5, object): ['아동기' < '청년' < '중년' < '장년' < '노년']

In [28]:
ret1,bins = pd.cut(personDF.age, bins=bins,labels=['아동기',"청년","중년","장년","노년"],right=True, retbins=True,include_lowest=True) #retbins 구간 
ret1 #include_lowest=True 제일 작은 놈만 포함


0    아동기
1    아동기
2     청년
3    아동기
4     청년
5     노년
6     청년
7     장년
8    아동기
9     청년
Name: age, dtype: category
Categories (5, object): ['아동기' < '청년' < '중년' < '장년' < '노년']

In [30]:
personDF ['cate_age'] = ret1

In [32]:
personDF.head()

name  age gender cate_age
0   홍길동    0      M      아동기
1   이나영    4      F      아동기
2   마징가   21      M       청년
3   변사또   20      M      아동기
4  원더우먼   38      F       청년

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [ ]:
#인코더 객체 생성

In [33]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)
OneHotEncoder(handle_unknown='ignore')
enc.categories_

#[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
enc.transform([['Female', 1], ['Male', 4]]).toarray()
# array([[1., 0., 1., 0., 0.],
#        [0., 1., 0., 0., 0.]])
enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])
# array([['Male', 1],
#        [None, 2]], dtype=object)
enc.get_feature_names_out(['gender', 'group'])
# array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'], ...)

array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'],
      dtype=object)

In [34]:
from sklearn.preprocessing import OneHotEncoder

#희소행렬

                                                                                                                                                            