Numpy 살펴보기
ndarrary 객체 생성 및 속성들 -------------------------------------------
np.array() 함수

In [1]:
import numpy as np

In [2]:
arr1 = np.array([11,22,33])
type(arr1), arr1

(numpy.ndarray, array([11, 22, 33]))

In [6]:
arr1.shape, arr1.ndim,arr1.dtype
#array에는 동일한 데이터 타입을 삽입해야한다.

((3,), 1, dtype('int32'))

In [7]:
arr2 = np.array([1,"A",0.34])
type(arr2), arr2, arr2.dtype
# U 유니코드 < : 

(numpy.ndarray, array(['1', 'A', '0.34'], dtype='<U32'), dtype('<U32'))

In [9]:
#3행 2열

arr3 = np.array([[0,0],[0,0],[0,0]])
type(arr3), arr3.ndim, arr3.dtype

(numpy.ndarray, 2, dtype('int32'))

In [14]:
# 0으로 원소값을 초기화 np.zeros(shape)
np.zeros((28,28))
np.zeros((28,28),dtype='int64')
# nparray는 기본이 float64로 저장


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
#원하는 숫자로 모든 원소값 초기화
arr6 = np.full((2,3),255)
arr6

array([[255, 255, 255],
       [255, 255, 255]])

In [20]:
# 연속된 범위 지정 원소 값 초기화 => np.arrange(시작, 종료, 간격)
arr7 = np.arange(1,10,2)
arr7

array([1, 3, 5, 7, 9])

In [21]:
arr1 = np.array([[2,2,2],[3,3,3]])
arr1

array([[2, 2, 2],
       [3, 3, 3]])

In [27]:
arr1.reshape(6,)


array([2, 2, 2, 3, 3, 3])

In [23]:
arr1.reshape(-1)

array([2, 2, 2, 3, 3, 3])

In [24]:
arr1.reshape(-1,2) #d열은 2개인데, 행은 니가 알아서해줘 

array([[2, 2],
       [2, 3],
       [3, 3]])

In [28]:
arr1.reshape(2,-1)

array([[2, 2, 2],
       [3, 3, 3]])

In [30]:
arr1.flatten() #1차원으로 바꿔주는것, 1차원으로 만들어주기 #펴주기 #copy#

array([2, 2, 2, 3, 3, 3])

In [31]:
arr1.ravel() #view ndasrra

array([2, 2, 2, 3, 3, 3])

In [32]:
import sklearn 

print(sklearn.__version__)

1.0.2


In [43]:
from sklearn.datasets import load_iris

iris = load_iris()
type(iris)

#Bunch 타입 #딕셔너니랑 비슷하다

iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [45]:
for key, value in iris.items():
    print(f'{key} , {value}')

data , [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9

In [48]:
type(iris['data']), type(iris['target']), type(iris['feature_names'])

(numpy.ndarray, numpy.ndarray, list)

In [53]:
#iris 2번
#판다스의 데이터 프레임으로 변환, 
iris, label = load_iris(return_X_y=True, as_frame=True)
type(iris),type(label)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [51]:
iris, label = load_iris(return_X_y=True)
type(iris),type(label)
print(label)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
#학습용 데이터 + 테스트용 데이터 준비
#좋은 방법 : 두 종류, 세 종류 데이터 따로 존재
#개선 방법 : 학습용 데이터를 분리해서 사용
                                                

In [54]:
iris.sample()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
119                6.0               2.2                5.0               1.5

In [76]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(iris,label) #비율 75: 25 


In [67]:
len(X_train)

120

In [113]:
X_test.shape, Y_test.shape,
len(X_train), len(Y_train)

#학습용 #검증용 #테스트
x_train, x_val, y_train, y_val = train_test_split(X_train,Y_train,test_size=0.2,random_state=22) 

# random_state=22 #데이터를 고정시켜둔다음에, 훈련을 시켜야한다.

In [65]:
len(x_train)

111

In [ ]:
# 학습 모델 생성
# 피처 : 라벨 => 지도 학습
# 라벨의 타입 => 범주형 -> 분류
# 분류 학습 방법 

In [68]:
from sklearn.tree import DecisionTreeClassifier

In [70]:
model = DecisionTreeClassifier()

# 학습용 데이터 사용
#### 모델객체변수명.fit()

In [120]:
model.fit(X_train,Y_train)

KNeighborsClassifier()

In [121]:
# 성능평가 <= 테스트데이터
# 모델 객체변수명
# 모델에 테스트 데이터를 입력 => 
model.score(X_test,Y_test)

c:\Users\seo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9736842105263158

In [122]:
y_pre = model.predict(X_test)
len(y_pre)

c:\Users\seo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


38

In [78]:
# 성능평가모듈 #매트릭스
# accuracy_score()
from sklearn.metrics import accuracy_score


In [123]:
# 몇개를 맞추었는지 비율로 알려줌 #정답 비율 #정답 갯수 normalize=False
accuracy_score(y_pre,Y_test, normalize=False)
accuracy_score(y_pre,Y_test)

0.9736842105263158

In [107]:
new_data = [1.2,3.2,0.4,2.9]#1행 4열짜리 만들어줘야한다. #2차원으로 만들어줘야한다. 

new_data = np.array(new_data).reshape(1,-1) #1행 4열 #1행으로 나머지는 -1(다행으로 만들어주삼)

model.predict(new_data)

#2차원으로 바꿔주는 다른 이름
# new_data = [1.2,3.2,0.4,2.9]
# model.predict([new_data])


c:\Users\seo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [108]:
# 학습 모델 생성
from sklearn.svm import SVC
model = SVC()


In [119]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()