Numpy 살펴보기
ndarrary 객체 생성 및 속성들 -------------------------------------------
np.array() 함수

In [1]:
import numpy as np

In [2]:
arr1 = np.array([11,22,33])
type(arr1), arr1

(numpy.ndarray, array([11, 22, 33]))

In [6]:
arr1.shape, arr1.ndim,arr1.dtype
#array에는 동일한 데이터 타입을 삽입해야한다.

((3,), 1, dtype('int32'))

In [7]:
arr2 = np.array([1,"A",0.34])
type(arr2), arr2, arr2.dtype
# U 유니코드 < : 

(numpy.ndarray, array(['1', 'A', '0.34'], dtype='<U32'), dtype('<U32'))

In [9]:
#3행 2열

arr3 = np.array([[0,0],[0,0],[0,0]])
type(arr3), arr3.ndim, arr3.dtype

(numpy.ndarray, 2, dtype('int32'))

In [14]:
# 0으로 원소값을 초기화 np.zeros(shape)
np.zeros((28,28))
np.zeros((28,28),dtype='int64')
# nparray는 기본이 float64로 저장


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
#원하는 숫자로 모든 원소값 초기화
arr6 = np.full((2,3),255)
arr6

array([[255, 255, 255],
       [255, 255, 255]])

In [20]:
# 연속된 범위 지정 원소 값 초기화 => np.arrange(시작, 종료, 간격)
arr7 = np.arange(1,10,2)
arr7

array([1, 3, 5, 7, 9])

In [21]:
arr1 = np.array([[2,2,2],[3,3,3]])
arr1

array([[2, 2, 2],
       [3, 3, 3]])

In [27]:
arr1.reshape(6,)


array([2, 2, 2, 3, 3, 3])

In [23]:
arr1.reshape(-1)

array([2, 2, 2, 3, 3, 3])

In [24]:
arr1.reshape(-1,2) #d열은 2개인데, 행은 니가 알아서해줘 

array([[2, 2],
       [2, 3],
       [3, 3]])

In [28]:
arr1.reshape(2,-1)

array([[2, 2, 2],
       [3, 3, 3]])

In [30]:
arr1.flatten() #1차원으로 바꿔주는것, 1차원으로 만들어주기 #펴주기 #copy#

array([2, 2, 2, 3, 3, 3])

In [31]:
arr1.ravel() #view ndasrray

array([2, 2, 2, 3, 3, 3])